export const CITIES = [
  {
    id: "1",
    hotel_id: "-510625",
    flight_id: "KRK.AIRPORT",
    name: "Kraków",
  },
  {
    id: "2",
    hotel_id: "-534433",
    flight_id: "WAW.CITY",
    name: "Warszawa",
  },
  {
    id: "3",
    hotel_id: "-537080",
    flight_id: "WRO.AIRPORT",
    name: "Wrocław",
  },
  {
    id: "4",
    hotel_id: "-126693",
    flight_id: "ROM.CITY",
    name: "Rzym",
  },
  {
    id: "5",
    hotel_id: "-1456928",
    flight_id: "PAR.CITY",
    name: "Paryż",
  },
  {
    id: "6",
    hotel_id: "-2601889",
    flight_id: "LON.CITY",
    name: "Londyn",
  },
  {
    id: "7",
    hotel_id: "-1746443",
    flight_id: "BER.AIRPORT",
    name: "Berlin",
  },
  {
    id: "8",
    hotel_id: "-390625",
    flight_id: "MAD.AIRPORT",
    name: "Madryt",
  },
  {
    id: "9",
    hotel_id: "-372490",
    flight_id: "BCN.AIRPORT",
    name: "Barcelona",
  },
  {
    id: "10",
    hotel_id: "-755070",
    flight_id: "IST.CITY",
    name: "Istambuł",
  },
  {
    id: "11",
    hotel_id: "-2173088",
    flight_id: "OPO.AIRPORT",
    name: "Porto",
  },
  {
    id: "12",
    hotel_id: "-2738479",
    flight_id: "LCA.AIRPORT",
    name: "Larnaka",
  },
  {
    id: "13",
    hotel_id: "-814876",
    flight_id: "ATH.AIRPORT",
    name: "Ateny",
  },
  {
    id: "14",
    hotel_id: "-96492",
    flight_id: "SPU.AIRPORT",
    name: "Split",
  },
  {
    id: "15",
    hotel_id: "-108649",
    flight_id: "TIA.AIRPORT",
    name: "Tirana",
  },
  {
    id: "16",
    hotel_id: "-1995499",
    flight_id: "VIE.AIRPORT",
    name: "Wiedeń",
  },
  {
    id: "17",
    hotel_id: "-850553",
    flight_id: "BUD.AIRPORT",
    name: "Budapeszt",
  },
];
